name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      DOCKERHUB_USERNAME:
        description: "DOCKERHUB USERNAME"
        required: true
      DOCKERHUB_TOKEN:
        description: "DOCKERHUB TOKEN"
        required: true
      IMAGENAME:
        description: "IMAGE NAME"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.event.inputs.DOCKERHUB_USERNAME }}
          password: ${{ github.event.inputs.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ github.event.inputs.DOCKERHUB_USERNAME }}/${{ github.event.inputs.IMAGENAME }}:dev .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ github.event.inputs.DOCKERHUB_USERNAME }}/${{ github.event.inputs.IMAGENAME }}:dev
